language: python

os:
  - linux

python:  
  - "3.9"

install:
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install -r requirements.txt
  - pip install .
  - pip install 'pytest>=3.9'
  - pip install pytest-cov coverage coveralls

script:
  - pytest --cov seglearn

after_success:
  - coveralls
